### ISSUE TITLE
Message shoveling failure when retrying a failed message and using queue name prefixes

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.MessagingBridge#230] opened 2023-03-10 08:45 UTC
## Description

MSMQ-based system on one side, RabbitMQ on the other side. MSMQ uses queue name prefixes to identify "environments." For example, the Sales endpoint is, in reality, `ENV.Sales` where ENV is the environment (Test, QA, PreProd, Prod, etc.)
On the RabbitMQ side, the intention is to use virtual hosts to define environments.

The Bridge configuration becomes clunky very quickly. The error and audit queues sit on the MSMQ side (using the same naming convention with the prefix).

If a message fails on the RabbitMQ side, it is correctly shoveled to the MSMQ error queue, and the FailedQ header is updated as expected. However, when the message is retried, the bridge fails in shoveling the message to the RabbitMQ side, complaining that an endpoint mapping is missing.

## Expected behavior

The message is correctly shoveled.

## Actual behavior

It fails, and the message is moved to the `bridge.error` queue.

## Versions

Please list the version of the relevant packages or applications in which the bug exists.

```xml
<PackageReference Include="NServiceBus.RabbitMQ" Version="8.0.1" />
<PackageReference Include="NServiceBus.Transport.Bridge" Version="1.0.2" />
<PackageReference Include="NServiceBus.Transport.Msmq" Version="2.0.0" />
```

### Steps to reproduce

I have a repro I can share privately.

**Comment by danielmarbach** [comment] 2023-08-09 14:08
We have started working on the issue and will keep this issue up to date

**Comment by danielmarbach** [comment] 2023-08-11 09:39
We are closing the issue because we have not been able to reproduce the mentioned bug with the supported versions. We have tested the following scenario on two independent reproduction environments and have observed the messages being correctly shoveled over the bridge.

The scenario is that when you use prefixes in your queues on the MSMQ side and on RabbitMQ vhosts to isolate environments. As an example, there is a Sales endpoint on MSMQ side and a Finance endpoint on the Rabbit side. Audit and error queue are on MSMQ side.

With prefixing the queues would on MSMQ look like

- Test.Sales
- Test.audit
- Test.error

and on Rabbit side under the vhost "Test¨

- Finance

The following bridge configuration would cover that.

```
var rabbitBridgeTransport = new BridgeTransport(new RabbitMQTransport(RoutingTopology.Conventional(QueueType.Quorum), "host=localhost;VirtualHost=Test"))
                {
                    AutoCreateQueues = true
                };

                rabbitBridgeTransport.HasEndpoint("Finance");
                bridgeConfiguration.AddTransport(rabbitBridgeTransport);

                var msmqBridgeTransport = new BridgeTransport(new MsmqTransport())
                {
                    AutoCreateQueues = true
                };
                
                msmqBridgeTransport.HasEndpoint("Test.Sales");
                msmqBridgeTransport.HasEndpoint("Test.error");
                bridgeConfiguration.AddTransport(msmqBridgeTransport);
```

We have been able to move failed messages back over the bridge without any problem and feel there is no bug anymore or the bug has been fixed with various updates. We used the 1.0.3 and 2.x versions of the bridge.

**Closed by danielmarbach** 2023-08-11 09:39 UTC
Labels: Bug
